name: Deploy to InfinityFree

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v4

      # 1. Siapkan environment Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # LTS — hilangkan peringatan deprecated Node.js 20

      # 2. Install semua dependency (Three.js, Vite, dll)
      - name: Install Dependencies
        run: npm install

      # 3. Lakukan proses Build (Mengubah .ts jadi .js dan memaketkan aset)
      - name: Build Project
        run: npm run build

      # 4. Unggah HANYA folder hasil build (misal: dist) ke server FTP
      - name: Sync Files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          local-dir: ./dist/ # PENTING: Arahkan ke folder hasil build (Vite menggunakan folder 'dist')
          dangerous-clean-slate: false